### ISSUE TITLE
Allow disabling or removing cloud-init

### ISSUE THREAD

**Issue by zedtux** [Numergy/cloud-init-cookbook#3]
I don't want to use cloud-init on my servers and I'd like chef to remove it.

`cloud-init` can [be disabled](https://askubuntu.com/a/1047618/149516) but also [removed](https://askubuntu.com/a/1068584/149516).

It would be great that this cookbook allows to disable or remove it.

**Comment by Sliim** [comment]
Hello @zedtux 

Thx for the suggestion, I added the `cloud_init` resource in version `0.3.0` to manage `cloud-init` package, now we can:
- enable/disable `cloud-init` by manipulating the `/etc/cloud/cloud-init.disabled` file.
- install/remove/purge `cloud-init` package (the `:purge` action will also remove configuration directories).

Also added some recipes that use this resource.
